# Generated by Django 6.0.2 on 2026-02-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0002_fooditem_extra_details_fooditem_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(
                choices=[
                    ('Pending', 'Pending'),
                    ('Processing', 'Processing'),
                    ('Ready', 'Ready'),
                    ('Delivering', 'Delivering'),
                    ('Delivered', 'Delivered'),
                ],
                default='Pending',
                max_length=20,
            ),
        ),
    ]
