# Generated by Django 6.0.2 on 2026-03-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_app", "0005_order_customer_email_and_rejected_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="delivery_request_pending",
            field=models.BooleanField(default=False),
        ),
    ]
