# Generated by Django 6.0.2 on 2026-03-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0006_user_delivery_request_pending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Processing', 'Processing'), ('Ready', 'Ready'), ('Delivering', 'Delivering'), ('Delivered', 'Delivered'), ('Received', 'Received')], default='Pending', max_length=20),
        ),
    ]
